# Generated by Django 5.0.6 on 2024-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='autor_name',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(upload_to='media/author'),
        ),
    ]
