# Generated by Django 5.0.6 on 2024-08-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_autor_name_author_author_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
