# Generated by Django 5.0.6 on 2024-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_course_created_at_remove_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_profile', models.ImageField(upload_to='media/author')),
                ('author_name', models.CharField(max_length=100)),
                ('about_author', models.CharField(max_length=200)),
            ],
        ),
    ]
