# Generated by Django 5.0.6 on 2024-12-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
