# Generated by Django 5.0.6 on 2024-12-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_categories',
            old_name='Category',
            new_name='category',
        ),
    ]
