# Generated by Django 5.0.6 on 2024-12-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_contact_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
