# Generated by Django 5.0.6 on 2024-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('fax', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '1. Contact_info',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Links',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': '3. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': '6. Contact_us'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Product'},
        ),
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': '4. Sub_categories'},
        ),
    ]
