# Generated by Django 5.0.6 on 2024-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contact_info_links_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='fax',
            field=models.IntegerField(null=True),
        ),
    ]
