# Generated by Django 5.0.6 on 2024-10-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_requirement_what_you_learn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='courese',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='what_you_learn',
            old_name='courese',
            new_name='course',
        ),
    ]
