# Generated by Django 5.0.6 on 2024-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_author',
            field=models.TextField(),
        ),
    ]
