# Generated by Django 5.0.6 on 2024-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_contact_info_fax_alter_contact_info_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='fax',
            field=models.CharField(default='', max_length=15),
        ),
    ]
