# Generated by Django 5.0.6 on 2024-10-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_language_course_ceartificate_course_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
