# Generated by Django 5.0.6 on 2024-12-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_contact_info_fax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_info',
            old_name='fax',
            new_name='fax_no',
        ),
    ]
