# Generated by Django 5.0.6 on 2024-10-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_language_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ceartificate',
            new_name='certificate',
        ),
    ]
