# Generated by Django 5.0.6 on 2024-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_fax_contact_info_fax_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='fax_no',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
