# Generated by Django 5.0.6 on 2024-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_contact_info_fax_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='fax_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
