# Generated by Django 5.0.6 on 2024-12-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contact_info_fax_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='fax_no',
        ),
    ]
