# Generated by Django 5.0.6 on 2024-12-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '5. Brand'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': '7. Contact_us'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '8. Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '6. Product'},
        ),
    ]
