# Generated by Django 5.0.6 on 2024-12-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_brand_options_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'out of stock')], max_length=100, null=True),
        ),
    ]
