# Generated by Django 5.0.6 on 2024-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_product_condition_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('refurbished', 'refurbished')], max_length=100, null=True),
        ),
    ]
