# Generated by Django 5.0.6 on 2024-12-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ecommerce/slider_img')),
                ('offer_img', models.ImageField(null=True, upload_to='ecommerce/slider_offer_img')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': '3. Links',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '6. Brand'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': '4. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': '8. Contact_us'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '9. Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '7. Product'},
        ),
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': '5. Sub_categories'},
        ),
    ]
