# Generated by Django 5.0.6 on 2025-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_slider_alter_brand_options_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ecommerce/slider_file')),
            ],
            options={
                'verbose_name_plural': '3. Slider',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
    ]
