# Generated by Django 5.0.6 on 2025-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_slide_alter_slider_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '3. Slider'},
        ),
    ]
