# Generated by Django 5.0.6 on 2025-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_slide_alter_slider_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
