# Generated by Django 5.0.6 on 2025-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='Total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
