# Generated by Django 5.0.6 on 2025-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_cart_item_total_price_alter_cart_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
