# Generated by Django 5.0.6 on 2025-03-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_cart_item_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_item',
        ),
    ]
