# Generated by Django 5.0.6 on 2025-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecommerce/cart')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('Total_price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': '10.Cart_item',
            },
        ),
    ]
