# Generated by Django 5.0.6 on 2025-03-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_cart_cartitem_delete_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
