# Generated by Django 5.0.6 on 2025-03-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
