# Generated by Django 5.0.6 on 2025-03-31 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
