# Generated by Django 5.0.6 on 2025-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
