# Generated by Django 5.0.6 on 2025-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_customer_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User_info',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user_info',
        ),
    ]
