# Generated by Django 5.0.6 on 2025-04-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_rename_customer_user_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_info',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
