# Generated by Django 5.0.6 on 2025-04-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_info'),
        ),
    ]
