# Generated by Django 5.0.6 on 2025-04-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_order_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='username',
        ),
    ]
