# Generated by Django 5.0.6 on 2025-04-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_rename_user_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
