# Generated by Django 5.0.6 on 2025-04-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_rename_username_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='username',
            new_name='user_name',
        ),
    ]
