# Generated by Django 5.0.6 on 2025-04-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_rename_username_user_info_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name_plural': '10. Order'},
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='user_name',
            new_name='username',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
