# Generated by Django 5.0.6 on 2025-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_user_info_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
