# Generated by Django 5.0.6 on 2025-04-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_user_info_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': '10. Order'},
        ),
    ]
