# Generated by Django 5.0.6 on 2025-04-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_contact_us_options_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_name',
            new_name='user',
        ),
    ]
