# Generated by Django 5.0.6 on 2025-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_user_info_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Unpaid', max_length=10, null=True),
        ),
    ]
