# Generated by Django 5.2.1 on 2025-06-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_order_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '5. Brand'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '10. Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': '11. CartItem'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': '3. Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': '7. Contact_us'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '9. Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '6. Product'},
        ),
        migrations.AlterModelOptions(
            name='sub_categories',
            options={'verbose_name_plural': '4. Sub_categories'},
        ),
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name_plural': '8. User_info'},
        ),
    ]
