# Generated by Django 5.2.1 on 2025-06-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
