# Generated by Django 5.2.1 on 2025-06-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_info_mobile_alter_user_info_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='villege',
            new_name='village',
        ),
    ]
