# Generated by Django 5.2.1 on 2025-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_villege_user_info_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
