# Generated by Django 5.2.1 on 2025-06-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_info_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
