# Generated by Django 5.2.1 on 2025-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_pin_code_user_info_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='village',
            field=models.CharField(default='', max_length=20),
        ),
    ]
