# Generated by Django 5.2.1 on 2025-06-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_info_city_alter_user_info_village'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
