# Generated by Django 5.2.1 on 2025-06-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brand_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
