# Generated by Django 5.2.1 on 2025-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_discount_alter_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(upload_to='images/prod_images'),
        ),
    ]
