# Generated by Django 5.2.1 on 2025-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(height_field='1080', upload_to='images/prod_images', width_field='920'),
        ),
    ]
