# Generated by Django 5.2.1 on 2025-06-07 11:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(upload_to='images/prod_images', validators=[app.models.validate_image_dimensions]),
        ),
    ]
