# Generated by Django 5.2.1 on 2025-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
