# Generated by Django 5.2.1 on 2025-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
