# Generated by Django 5.2.1 on 2025-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_shipping_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_charge',
            field=models.FloatField(default=0, null=True),
        ),
    ]
