# Generated by Django 5.2.1 on 2025-06-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_shipping_alter_product_shipping_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shipping',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shipping_charge',
            new_name='delivery_charge',
        ),
    ]
