# Generated by Django 5.2.1 on 2025-06-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pro_total',
            field=models.FloatField(),
        ),
    ]
