# Generated by Django 5.2.1 on 2025-06-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_order_pro_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(),
        ),
    ]
