# Generated by Django 5.2.1 on 2025-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_one_day_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '6. Cart'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': '7. CartItem'},
        ),
        migrations.AlterModelOptions(
            name='one_day_deal',
            options={'verbose_name_plural': '5. One_day_deal'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '8. Order'},
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='one_day_deal',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
