# Generated by Django 5.2.1 on 2025-06-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_day_deal',
            name='field',
            field=models.CharField(default='one_day', editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field',
            field=models.CharField(default='product', editable=False, max_length=20, null=True),
        ),
    ]
