# Generated by Django 5.2.1 on 2025-06-22 05:10

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_one_day_deal_field_product_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one_day_deal',
            old_name='product',
            new_name='title',
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='brand',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='category',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categories'),
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='delivery',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='delivery_charge',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='one_day_deal',
            name='prod_image',
            field=models.ImageField(editable=False, null=True, upload_to='images/one_day', validators=[app.models.validate_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='one_day_deal',
            name='offer_price',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='one_day_deal',
            name='price',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
    ]
