# Generated by Django 5.2.1 on 2025-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_product_one_day_deal_title_one_day_deal_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_day_deal',
            name='c',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
