# Generated by Django 5.2.1 on 2025-06-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_one_day_deal_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='one_day_deal',
            old_name='c',
            new_name='product',
        ),
    ]
