# Generated by Django 5.2.1 on 2025-06-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_c_one_day_deal_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='one_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.one_day_deal'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
